### ISSUE TITLE
有什么同样耐用的智能手机呢？

### ISSUE THREAD

**Issue by otakutyrant** [deapplization/awesome-switching#1]
我用过三代 Google 旗舰手机，但平均寿命不到两年，我对如此又烧钱又频繁的更新换代感到厌倦，就买了寿命公认超长的 iPhone。那么迁移问题来了：有什么同样耐用的智能手机呢？

显然要能装 Android 或 iOS app，我很依赖讯飞听见这样的 app。

**Comment by huo-ju** [comment]
https://www.tomsguide.com/us/old-phones-unsafe,news-24846.html 这几年Android也提供超过4年的安全补丁了，主要是硬件配置比较高，不像早年因为内存2G限制无法支持新系统。现在Google/三星都明确提供了至少4年安全补丁。中国厂商我还不太了解升级策略。

其它品牌也可以考虑社区提供的rom版本（相对来说肯定不如厂商提供的可靠）

**Comment by eastwoodnet** [comment]
我是自从有安卓手机那一天起就一直使用安卓的用户，手机退休多数是因为性能和存储容量以及电池待机不能满足需求了。并没有因为损坏更换过手机。所以所谓了手机寿命和用户习惯也算是有一定的关系。单纯从硬件和性能上选择安卓机型的理由我有几个共参考。
1、选择高通芯片的机型，
高通芯片一般拥有较强的实力，相对在开源领域也较为友好，一些主流手机型号即使原厂不提供安全补丁以后，也有类似LineageOS这种第三方ROM提供系统升级和安全更新。具体可以LineageOS的网站看看机型支持来寻找答案。
2、选择大厂有海外型号的机型，
有海外的型号一般意味着手机的ROM由于欧盟GDPR的影响，会有很多可以刷机的机会，这就给用户有了选择权。例如8之前的一加手机，可以不用解锁Bootloader直接刷成氧OS。既不用担心解锁bootloader带来的安全隐患，也不会失去保修。
3、选择手机设计结构较为简单的机型，
结构简单意味着维修方便，由于近年来手机多为内置电池，使用一段时间后电池效能下降，但手机性能并无问题，可以选择自行更换电池，方便的拆机方法能够减少更换电池的失败率。

**Comment by otakutyrant** [comment]
@eastwoodnet 你用过的 Android 手机一般有多久？@huo-ju 强调官方支持生命周期有四年，但很可惜我所有用过旗舰手机都是物理损坏，用着用着就突然黑屏，并且再也开不起来了。我猜可能因为用的充电器和我海淘的旗舰手机之间的兼容性不好

**Comment by huo-ju** [comment]
@otakutyrant  我指的四年是官方提供升级的时间，超过这个时间仍然可以选择社区维护的版本。(超过官方维护时间之后ios无法再获得升级了)

官方升级的好处是比较可靠，尤其是驱动相关部分存在不开源部分，如果驱动被发现了重大安全漏洞，就需要从官方获得升级。如果只是系统本身的安全补丁，社区维护的版本也没问题。

**Comment by MetroWind** [comment]
已买 Pixel 4a，便宜所以坏了也不可惜，这大概也是一种解决方法吧⋯⋯

**Comment by otakutyrant** [comment]
@MetroWind Pixel 4a 算旗舰手机吗？我最后一次用的是 Google Pixel 3，好久没关注后续产品了。

**Comment by MetroWind** [comment]
4a 不是旗舰，a 系列是廉价版，相当于水果的 SE。

**Comment by otakutyrant** [comment]
@eastwoodnet 这么好，iPhone 坏掉时我再按你分享的原则莱买手机
